version: '3'

services:
  consul:
    image: consul
    build: consul
    ports:
      - "12394:8500"
    expose:
      - "8500"
    networks:
      internal:
        ipv4_address: 172.16.238.150

  orchestrator:
    image: orchestrator
    build: orchestrator
    expose:
      - "31456"
    depends_on:
      - consul
    networks:
      internal:
        ipv4_address: 172.16.238.200

  mysql:
    image: "mysql:5.7"
    build: mysql
    expose:
      - "3306"
    depends_on:
      - orchestrator
    networks:
      - internal 
  
  proxysql1:
    image: proxysql
    build: proxysql
    expose:
      - "6032"
      - "6080"
    depends_on:
      - mysql
    networks:
      internal:
        ipv4_address: 172.16.238.2
      
  proxysql2:
    image: proxysql
    build: proxysql
    expose:
      - "6032"
      - "6080"
    depends_on:
      - proxysql1
    networks:
      internal:
        ipv4_address: 172.16.238.3
  
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/16
        
volumes:
  mysql_master_data:
    driver: local
